### PR TITLE
Enable admin to assign guest orders to customers

### PR DESCRIPTION
**Pull request by mystix**
- update full customer info when converting orders (e.g. DOB, first name, last name etc)
- removed defunct email address check in admin controller
- fixed error message display when a customer attempts to assign an invalid order ID

### CODE REVIEW

**Comment by srenon** [comment]
@mystix .... Also not a fan of the auto merge (https://www.mailjet.com/blog/news/8-lessons-learned-from-yahoo-s-bold-move-of-recycling-inactive-email-addresses/) .... could you either create a system config setting or my original idea was to create a review page so the admin user could double check to make sure the order belongs to the same customer

**Comment by mystix** [comment]
> @mystix ... Thanks for the PR
> 
> Could you change the `$history->save()` to something like https://github.com/magepal/magento2-edit-order-email/blob/master/Controller/Adminhtml/Edit/Index.php#L137
> 
> Also, if converted by admin then append the admin username and if converted by guest then add converted by use

Good idea. Added in commit 10b241d6ddb41b2824b1d700802c64e99ee3fdec

**Comment by mystix** [comment]
> @mystix .... Also not a fan of the auto merge (https://www.mailjet.com/blog/news/8-lessons-learned-from-yahoo-s-bold-move-of-recycling-inactive-email-addresses/) .... could you either create a system config setting or my original idea was to create a review page so the admin user could double check to make sure the order belongs to the same customer

Will look into system config setting(s) (on a per-customer-field basis, if that makes sense -- let me know your thoughts?).

Allowing only admins to review guest order conversions doesn't make sense (to me at least) since
- the steps involved are essentially the same for customers as well as admins
- we're grouping orders belonging to the same customer by email address, which should rightfully uniquely identify customers

[edit]
~Did I miss something?~
Are you referring to situations where guests fat-finger their email addresses and the incorrect address just so happens to belong to someone else?

**Comment by srenon** [comment]
@mystix ... send me an email hello@magepal.com, I look for someone to help me with some M1 to M2 projects

**Comment by mystix** [comment]
> @mystix .... Also not a fan of the auto merge (https://www.mailjet.com/blog/news/8-lessons-learned-from-yahoo-s-bold-move-of-recycling-inactive-email-addresses/) .... could you either create a system config setting or my original idea was to create a review page so the admin user could double check to make sure the order belongs to the same customer

added auto-merge configs in commit 638f3332b3144ebbdc30c27b6332d736e40bce05

**Comment by mystix** [comment]
Is this good enough to be merged? 😄

**Comment by srenon** [comment]
Yea... give me a few days.... 

keep in mind that the merge customer data (vat, dob) is merging from customer to order so the only time it will not be blank is if the customer already exists and would not solve https://github.com/magepal/magento2-guest-to-customer/issues/7

**Comment by srenon** [comment]
@mystix ... did you get my email?

**Comment by mystix** [comment]
> @mystix ... did you get my email?

Yes I did -- just replied you yesterday. Did you receive it?

**Pull request merged**
